# syntax = docker/dockerfile:latest

# Base image
FROM node:18

# Set up environment
ENV DEBIAN_FRONTEND noninteractive

# Update and install base packages
RUN apt-get update -qq && \
    apt-get install -y \
                    curl \
                    wget

# Install the latest version of Node.js and Yarn
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Set up the working directory
WORKDIR /root/work

# Default command
CMD ["./bin/vite", "dev"]

